name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # if you generate docs:
          pip install sphinx mkdocs

      - name: Run unit tests
        run: |
          pytest -q --disable-warnings --maxfail=1

      - name: Check code formatting with isort
        run: |
          isort --check-only --verbose .

      - name: Lint with flake8
        run: |
          flake8 .

      - name: Build documentation (mkdocs)
        if: ${{ always() }}
        run: |
          mkdocs build --strict
