# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 isort black pre-commit

      - name: Run pre-commit hooks
        run: pre-commit run --all-files

      - name: Lint with flake8
        run: flake8 .

      - name: Check import ordering with isort
        run: isort --check-only .

      - name: Check code formatting with Black
        run: black --check .

      - name: Run tests
        run: pytest -q --disable-warnings --maxfail=1
